Gridless integration points + postprocessing
rath3t/dune-iga pull request #14
Opened 2023-07-17 17:26 UTC by henrij22

2023-07-17 17:27 UTC, henrij22 commented
Still Work in Progress!

2023-07-24 09:33 UTC, henrij22 commented
From my side: It should be ready

2023-07-27 13:35 UTC, rath3t commented on dune/iga/io/igadatacollector.hh
> +        for (auto& subGridVertex : geometries_.getVertices(elementId))
This can be simplified to: `for (std::size_t vIdx = 0; auto& subGridVertex : geometries_.getVertices(elementId))`

2023-07-27 13:36 UTC, rath3t commented on dune/iga/io/igadatacollector.hh
> +        for (auto& subGridVertex : geometries_.getVertices(elementId)) {
same as above

2023-07-27 13:38 UTC, rath3t commented on dune/iga/io/igarefinedgeometries.hh
> +        return trimmedElementData_.at(eIndex).indices[subEleIndex * 3 + subEntityIndex];
Can you write a comment here that  the 3 and 4 stem from the choice to only allow triangles and quads and that these numbers are their vertex counts? (also indicate this through variable names

2023-07-27 13:39 UTC, rath3t commented on dune/iga/nurbsgeometry.hh
> +    using SubGridType = GridImpl::Traits::SubGridType;
Yes nice better name!

2023-07-27 13:40 UTC, rath3t commented on dune/iga/nurbsgridtraits.hh
> +  using SubGridType = Dune::IGA::TrimmedSubGrid<2>;
nice cleanup

2023-07-27 13:48 UTC, rath3t requested changes
Looks good to me. Only the minor given things should be fixed

2023-08-16 16:27 UTC, rath3t approved these changes

2023-08-16 16:27 UTC, merged